export { default as GlobalStyle } from './global-style'
export { default as Layout } from './layout'
export { default as Header } from './header'
export { default as Aside } from './aside'
export { default as Main } from './main'
